package command;

import java.util.Collections;
import java.util.List;

/**
 * A Data Transfer Object (DTO) encapsulating the syntactic breakdown of user input.
 * It strictly holds immutable data generated by the CommandParser, ensuring that
 * downstream commands receive a predictable and unaltered grammatical structure.
 */
public class ParsedCommand {
    private final String verb;
    private final List<String> args;
    private final String preposition;
    private final List<String> secondaryArgs;

    public ParsedCommand(String verb, List<String> args, String preposition, List<String> secondaryArgs) {
        this.verb = verb;
        this.args = args;
        this.preposition = preposition;
        this.secondaryArgs = secondaryArgs;
    }

    public String getVerb() { 
        return verb; 
    }

    /** @return An unmodifiable view of the primary arguments to enforce immutability. */
    public List<String> getArgs() { 
        return Collections.unmodifiableList(args); 
    }

    public String getPreposition() { 
        return preposition; 
    }

    /** @return An unmodifiable view of the secondary arguments (post-preposition). */
    public List<String> getSecondaryArgs() { 
        return Collections.unmodifiableList(secondaryArgs); 
    }
    
    /**
     * Utility method for quick access to the primary target noun.
     * @return The first argument, or null if the list is empty.
     */
    public String getFirstArg() { 
        return args.isEmpty() ? null : args.get(0); 
    }

    /**
     * Utility method for quick access to the secondary target noun (e.g., the key in "unlock door with key").
     * @return The first secondary argument, or null if the list is empty.
     */
    public String getSecondArg() { 
        return secondaryArgs.isEmpty() ? null : secondaryArgs.get(0); 
    }
}